---
- name: Template out gitconfig
  template: src=gitconfig.j2 dest=~/.gitconfig force=yes

- name: Ensure dotfile parent folders exist
  file: path=~/.{{ item }} state=directory
  with_items: "{{ dotfiles.add_folders }}"
  when: dotfiles.add_folders is defined

- name: Remove existing folders to be symlinked
  file: path=~/.{{ item }} state=absent
  with_items: "{{ dotfiles.remove_folders }}"
  when: dotfiles.remove_folders is defined

- name: Symlink dotfiles
  file: src={{ dotfiles.filepath }}/{{ item.src }}.symlink dest=~/.{{ item.dest }} state=link force=yes
  with_items: "{{ dotfiles.links }}"
  when: dotfiles.links is defined

- name: Install Atom starred packages and themes
  shell: "apm stars --user {{ atom.stars_user }} --install"
  when: atom.stars_user is defined
