---
- name: Update pacman and the system
  become: yes
  pacman: update_cache=yes upgrade=yes

- name: Install packages (via Yaourt)
  yaourt: name={{ item }} state=latest
  with_items: "{{ system.packages }}"
  when: system.packages is defined and system.aur
  tags: packages

- name: Install packages (via Pacman)
  pacman: name={{ item }} state=latest
  with_items: "{{ system.packages }}"
  when: system.packages is defined and not system.aur
  tags: packages

- name: Run kernel modules for Vagrant Virtualbox
  become: yes
  shell: /sbin/rcvboxdrv setup

- name: Add kernel module load file
  become: yes
  template: src=virtualbox.conf dest=/etc/modules-load.d/virtualbox.conf